name: mika_test_2
channels:
  - conda-forge
  - defaults
variables:
  PYTHONNOUSERSITE: "1"
dependencies:
  - python=3.10
  - pip=23.3.1
  - numpy==2.2.6
  - pandas==2.2.2
  - scipy==1.14.1
  - matplotlib==3.8.4
  - pillow==10.3.0
  - pyqtgraph==0.13.4
  - pyside6==6.7.0
  - statsmodels
  - scikit-learn
  - pip:
    - opencv-python
    - torch

